### ISSUE TITLE
BaseTotalAmount - total required is missing

### ISSUE THREAD

**Issue by pietrini** [pietrini/amadeus-android#10]
for call: https://test.api.amadeus.com/v2/shopping/hotel-offers?cityCode=PAR&adults=1&radius=5&radiusUnit=KM&paymentPolicy=NONE&includeClosed=false&bestRateOnly=true&view=FULL&sort=PRICE

Total field in BaseTotalAmount is missing and is marqued required in swagger definition. (I might be using an outdated definition).

  BaseTotalAmount:
    description: estimated nightly average for the stay
    type: object
    properties:
      base:
        description: Amount excluding taxes.
        type: string
        pattern: ^\\d+(\.\\d+)?$
      total:
        description: Amount including taxes.
        type: string
        pattern: ^\\d+(\.\\d+)?$
    required:
      - base
      - total

**Comment by anthonyroux** [comment]
Shared with the API product manager

**Comment by anthonyroux** [comment]
Swagger updated
