### ISSUE TITLE
TravelerPricing: fareOption is missing

### ISSUE THREAD

**Issue by pietrini** [pietrini/amadeus-android#13]
Call: INFO: --> GET https://test.api.amadeus.com/v1/booking/flight-orders/eJzTd9cPCzZ1CgsAAAtqAmw=

com.squareup.moshi.JsonDataException: Required value 'fareOption' missing at $.data.flightOffers[0].travelerPricings[1]

in TravelerPricing object fareOption is marqued mandatory but is absent from certain calls.

Swagger:
    travelerPricings:
        title: TravelerPricings
        description: Fare information for each traveler/segment
        type: array
        minItems: 1
        maxItems: 18
        items:
          title: TravelerPricing
          required:
            - travelerId
            - fareOption
            - travelerType
            - fareDetailsBySegment
          properties:
            travelerId:

**Comment by anthonyroux** [comment]
Swagger updated
