### ISSUE TITLE
BaseTotalAmount base field should be marked as optional in swagger

### ISSUE THREAD

**Issue by pietrini** [pietrini/amadeus-android#28]
url: https://test.api.amadeus.com/v2/shopping/hotel-offers?cityCode=MAD

base field isn't required as he is missing in some objects

**Comment by anthonyroux** [comment]
I think it has been fixed in the new version of swagger available 
![image](https://user-images.githubusercontent.com/713173/77899302-d0a1d780-727c-11ea-8178-ff273c3d0e6d.png)
