### ISSUE TITLE
API Coverage

### ISSUE THREAD

**Issue by pietrini** [pietrini/amadeus-android#8]
Search & Shopping
- [x] FlightOffersPrice_v1_Swagger_specification.json
- [x] FlightInspirationSearch_Swagger_specification.json
- [x] SeatMapDisplay_v1.2_Swagger_specification.json
- [x] Flight_Cheapest_Date_Search_Swagger_specification.json
- [x] FlightOffersSearch_v2_Swagger_specification.json

Booking
- [x] FlightOrderManagement_v1_Swagger_specification.json
- [x] FlightCreateOrders_v1_Swagger_specification.json

Artificial Intelligence
- [x] AirportOnTimePerformance_v1_Swagger_specification.json
- [x] FlightDelayPrediction_v1_Swagger_specification.json
- (Wait for v2) FlightChoicePrediction_v1_Swagger_specification.json

Travel Insights
- [x] FlightBusiestTravelingPeriod_Swagger_specification.json
- [x] FlightMostBookedDestinations_Swagger_specification.json
- [x] Flight_Most_Traveled_Destinations_Swagger_specification.json

Utilities
- [x] AirlineCodeLookup_Swagger_specification.json
- [x] AirportCitySearch_Swagger_specification.json
- [x] NearestRelevantAirports_Swagger_specification.json
- [x] Flight_Check-In_Links_Swagger_specification.json

Hotel
- [x] HotelBooking_v1_Swagger_specification.json
- [x] HotelRatings_v2_Swagger_specification.json
- [x] HotelSearch_v2_SS_Swagger_specification.json

Location - POI
- [x] PointsOfInterest_v1_Swagger_specification.json

Artificial Intelligence
- [x] TripPurposePrediction_v1_Swagger_specification.json
- [x] AIGeneratedPhotos_v2_Swagger_specification.json

Utilities
- [x] TripParser_v2_Swagger_specification.json

**Comment by anthonyroux** [comment]
Flight Choice Prediction: we are going to deploy version 2 of the API so don't worry too much about this one.

Flight Order Management: We publish a new version of the swagger last week (with a new endpoint)

Otherwise perfect! I think we did some updates in the model of Flight Offers Search / Price / Create orders but no worries we will treat them as any other updates (I will do the PR if needed)
